const Link = ({ href, ...props }: any) => <a href={href} {...props} />
import { ArrowUpRight, Check } from 'lucide-react'
import { MarketingFooter, MarketingHeader, SectionLabel, SignalPill } from '@/components/marketing'
import { consumerLendingLifecycle as lifecycle } from '@/lib/lifecycle'

type Locale = 'zh' | 'en'

const copy = {
  zh: { eyebrow: '解决方案 / 消费信贷', title: <>让每一份申请<br/><span className='text-[#8ce1cc]'>更清晰。</span></>, body: '在获客、核验、放款与贷后各个关键节点，补充新鲜的身份、欺诈、本地与 eKYC 信号；最终决策始终留在你的系统。', cta: '联系销售', pill: '提供信号，不替你决策', lifecycleEyebrow: '完整信贷生命周期', lifecycleTitle: '在每个决策时刻补足上下文。', lifecycleBody: '所有信号以结构化证据返回，直接供现有策略引擎消费。SIGNAL 提供风险信号，最终授信与运营决策由你的系统完成。', responsibleEyebrow: '默认负责任', responsibleTitle: '清晰的信号。清晰的边界。', responsible: ['Unknown 不等于 No Match 或“未注册”。', '工作台默认对标识符进行脱敏展示。', 'Provider 名称仅作为 SIGNAL 内部路由信息。', '营销演示不会查询真实数据。'], buildEyebrow: '构建你的决策层', buildTitle: '一套 API 契约，覆盖每一层信号。', products: '查看产品' },
  en: { eyebrow: 'Solution / Consumer lending', title: <>Make every application<br/><span className='text-[#8ce1cc]'>more legible.</span></>, body: 'Fresh identity, fraud, local and eKYC signals at every critical moment — without handing the decision away.', cta: 'Talk to Sales', pill: 'Signals, not decisions', lifecycleEyebrow: 'The lending lifecycle', lifecycleTitle: 'Context at the point of decision.', lifecycleBody: 'Use structured evidence inside the policy engine you already own. SIGNAL provides signals; your system makes the final decision.', responsibleEyebrow: 'Responsible by default', responsibleTitle: 'Clear signals. Clear boundaries.', responsible: ['Unknown is not the same as No Match or Not Registered.', 'Identifiers are masked by default in workspace views.', 'Provider names stay internal to SIGNAL.', 'Marketing demos never query real data.'], buildEyebrow: 'Build your decision layer', buildTitle: 'One API contract. Every signal you need.', products: 'Explore products' }
} as const

export default function ConsumerLending({ locale }: { locale: Locale }) {
  const t = copy[locale]
  return <main className='bg-[#f7faf9]'><div className='bg-[#10252d] text-white'><MarketingHeader dark locale={locale}/><div className='mx-auto max-w-[1440px] px-6 pb-24 pt-14 lg:px-12'><SectionLabel dark>{t.eyebrow}</SectionLabel><h1 className='mt-5 max-w-3xl text-5xl font-medium leading-[.98] tracking-[-.055em] sm:text-7xl'>{t.title}</h1><p className='mt-8 max-w-2xl text-lg leading-8 text-white/60'>{t.body}</p><div className='mt-9 flex flex-wrap gap-3'><Link href={locale === 'zh' ? '/zh/contact-sales' : '/en/contact-sales'} className='bg-[#8ce1cc] px-5 py-3.5 text-sm font-semibold text-[#10252d]'>{t.cta}<ArrowUpRight size={16} className='ml-2 inline'/></Link><SignalPill tone='teal'>{t.pill}</SignalPill></div></div></div><section className='mx-auto max-w-[1440px] px-6 py-20 lg:px-12 lg:py-28'><div className='grid gap-14 lg:grid-cols-[.7fr_1.3fr]'><div><SectionLabel>{t.lifecycleEyebrow}</SectionLabel><h2 className='mt-4 max-w-lg text-4xl font-medium tracking-[-.045em] text-[#10252d] sm:text-5xl'>{t.lifecycleTitle}</h2><p className='mt-6 max-w-md text-sm leading-7 text-[#61747b]'>{t.lifecycleBody}</p></div><div className='grid border-t border-[#d9e5e1] sm:grid-cols-2'>{lifecycle.map(step => <div key={step.no} className='border-b border-[#d9e5e1] py-6 pr-5'><span className='font-mono text-xs text-[#8b9ba0]'>{step.no}</span><h3 className='mt-3 text-base font-semibold text-[#10252d]'>{step[locale][0]}</h3><p className='mt-2 text-sm leading-6 text-[#61747b]'>{step[locale][1]}</p></div>)}</div></div></section><section className='border-y border-[#d9e5e1] bg-[#edf5f2]'><div className='mx-auto grid max-w-[1440px] gap-12 px-6 py-20 lg:grid-cols-2 lg:px-12'><div><SectionLabel>{t.responsibleEyebrow}</SectionLabel><h2 className='mt-4 text-4xl font-medium tracking-[-.045em] text-[#10252d]'>{t.responsibleTitle}</h2></div><div className='space-y-4 text-sm text-[#61747b]'>{t.responsible.map(item => <p key={item} className='flex items-start gap-3'><Check size={16} className='mt-0.5 text-[#0e8b83]'/>{item}</p>)}</div></div></section><section className='bg-[#10252d] text-white'><div className='mx-auto flex max-w-[1440px] items-end justify-between gap-8 px-6 py-16 lg:px-12'><div><SectionLabel dark>{t.buildEyebrow}</SectionLabel><h2 className='mt-4 text-3xl font-medium sm:text-4xl'>{t.buildTitle}</h2></div><Link href={locale === 'zh' ? '/zh/products' : '/en/products'} className='inline-flex items-center border border-[#8ce1cc]/60 px-5 py-3.5 text-sm font-semibold text-[#d9fff6]'>{t.products}<ArrowUpRight size={16} className='ml-2'/></Link></div></section><MarketingFooter locale={locale}/></main>
}
