'use client'
import { useState } from 'react'
import { Check, ChevronDown, Copy, Loader2 } from 'lucide-react'
export function Button({ children, variant='primary', className='', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary'|'ghost'|'outline' }) { const styles = { primary:'bg-ink text-white hover:bg-[#1b3948]', ghost:'text-ink hover:bg-[#eef4f2]', outline:'border border-[var(--line)] bg-white hover:border-teal' }; return <button className={'inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition '+styles[variant]+' '+className} {...props}>{children}</button> }
export function Logo() { return <div className="flex items-center gap-2 font-semibold tracking-[.18em] text-ink"><span className="grid h-7 w-7 place-items-center rounded-md bg-teal text-xs text-white">S</span>SIGNAL</div> }
export function ServiceMark({ mark, tone }: { mark:string; tone:string }) { return <span className={'grid h-8 w-8 place-items-center rounded-lg text-sm font-bold '+tone}>{mark}</span> }
export function Badge({ children, className='' }: {children:React.ReactNode; className?:string}) { return <span className={'inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold '+className}>{children}</span> }
export function CopyButton({ value }: {value:string}) { const [copied,setCopied]=useState(false); return <button aria-label="Copy" onClick={()=>{navigator.clipboard?.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)}} className="text-[var(--muted)] hover:text-ink">{copied?<Check size={15}/>:<Copy size={15}/>}</button> }
export function SelectBox({ value, onChange, children }: {value:string; onChange:(v:string)=>void; children:React.ReactNode}) { return <div className="relative"><select value={value} onChange={e=>onChange(e.target.value)} className="w-full appearance-none rounded-lg border border-[var(--line)] bg-white px-3.5 py-3 text-sm text-ink outline-none focus:border-teal">{children}</select><ChevronDown size={16} className="pointer-events-none absolute right-3 top-3.5 text-[var(--muted)]"/></div> }
export function LoadingState({ label = 'Querying signal network…' }: { label?: string }) { return <div className="flex items-center gap-2 text-sm text-[var(--muted)]"><Loader2 size={16} className="animate-spin text-teal"/>{label}</div> }
